version: '3.8'  # Docker Compose file version

services:
  openWebUI3:
    image: ghcr.io/open-webui/open-webui:cuda
    restart: always
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    container_name: my-open-webui
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: all

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
    container_name: my-ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: all

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    restart: always
    ports:
      - "9099:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - pipelines:/app/pipelines
    container_name: my-pipelines
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: all

volumes:
  ollama: {}
  open-webui: {}
  pipelines: {}