services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:cuda
    restart: always
    ports:
      - "${PORT_WEBUI}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./volumes/webui:/app/backend/data
    container_name: gpt.webui
    
  ### 파이프라인 ###
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: gpt.pipelines
    restart: always
    ports:
      - "${PORT_PIPLINE}:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./volumes/pipelines:/app/pipelines